<?php

/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 5/29/2017
 * Time: 9:21 AM
 */
class Oauth extends API_Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function token()
    {
        parent::token(); // TODO: Change the autogenerated stub
    }

    public function refresh_token()
    {
        parent::refresh_token(); // TODO: Change the autogenerated stub
    }

    public function authorize()
    {
        parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function authorize_2(){
        parent::authorize_2();
    }

    public function cb(){

    }
}