<?php

/**
 * Created by PhpStorm.
 * User: agungrizkyana
 * Date: 5/25/17
 * Time: 14:39
 */
class Resource extends API_Controller
{

    public function __construct()
    {
        parent::__construct();

    }

    public function token()
    {
        parent::token(); // TODO: Change the autogenerated stub
    }

    public function authorize()
    {
        parent::authorize(); // TODO: Change the autogenerated stub
    }

    public function refresh_token()
    {
        parent::refresh_token(); // TODO: Change the autogenerated stub
    }


}